/** @type {import('tailwindcss').Config} */
/** BoothBuzz — Stitch design tokens (project 8224948024289506766) */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        primary: '#3525cd',
        'primary-container': '#4f46e5',
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#dad7ff',
        'on-primary-fixed': '#0f0069',
        'on-primary-fixed-variant': '#3323cc',
        secondary: '#545f73',
        'secondary-container': '#d5e0f8',
        'secondary-fixed': '#d8e3fb',
        'secondary-fixed-dim': '#bcc7de',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#586377',
        'on-secondary-fixed': '#111c2d',
        'on-secondary-fixed-variant': '#3c475a',
        tertiary: '#3a4a54',
        'tertiary-container': '#51626c',
        'tertiary-fixed': '#d3e5f1',
        'tertiary-fixed-dim': '#b7c9d5',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ccdee9',
        'on-tertiary-fixed': '#0c1e26',
        'on-tertiary-fixed-variant': '#384953',
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-container': '#e5eeff',
        'surface-container-low': '#eff4ff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#4d44e3',
        'on-background': '#0b1c30',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#464555',
        outline: '#777587',
        'outline-variant': '#c7c4d8',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#c3c0ff',
        accent: '#4f46e5',
      },
      boxShadow: {
        editorial: '0 32px 64px rgba(11, 28, 48, 0.05)',
        'editorial-md': '0 32px 64px rgba(11, 28, 48, 0.08)',
      },
    },
  },
  plugins: [],
};
